# Generated by Django 2.2.17 on 2021-01-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Lee', max_length=30),
        ),
    ]
