# Generated by Django 3.1.5 on 2021-02-09 08:43

from django.db import migrations, models
import lmae.models


class Migration(migrations.Migration):

    dependencies = [
        ('lmae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('W', 'Female'), ('Mi-24', 'Attack Helicopter'), ('n/a', 'Not sure')], default='n/a', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=lmae.models.City.get_deleted_city, related_name='person', to='lmae.city'),
        ),
    ]
