# Generated by Django 3.1.5 on 2021-01-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmae', '0003_auto_20210122_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmae.city'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('W', 'Female'), ('Mi-24', 'Attack Helicopter'), ('n/a', 'Not sure')], default='wtf', max_length=10),
        ),
    ]
