# Generated by Django 3.1.5 on 2021-01-22 12:00

from django.db import migrations, models
import lmae.models


class Migration(migrations.Migration):

    dependencies = [
        ('lmae', '0004_auto_20210122_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default=lmae.models.Person.get_default_city, null=True, on_delete=lmae.models.Person.get_deleted_city, to='lmae.city'),
        ),
    ]
