# Generated by Django 3.1.5 on 2021-02-08 17:01

from django.db import migrations, models
import lmae.models


class Migration(migrations.Migration):

    dependencies = [
        ('lmae', '0005_auto_20210122_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=lmae.models.Person.get_deleted_city, related_name='person', to='lmae.city'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('W', 'Female'), ('Mi-24', 'Attack Helicopter'), ('n/a', 'Not sure')], default='n/a', max_length=10),
        ),
    ]
